services:
  google_business_review:
    build:
      context: ..
      dockerfile: google_business_review/Dockerfile
    container_name: google_business_review
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: "no"
